### PR TITLE
Added Web Development file.

### PR DESCRIPTION
**Pull request by Radhey644**
I have done the work of my part by adding content in the web dovelopment file.

### CODE REVIEW

**Comment by Iliveinbianries** [comment]
The content looks great, but please follow these steps:
- create a new folder Web
- inside it create your file Web/WhatIsWebDevelopement.md

follow this and resubmit.

**Comment by Radhey644** [comment]
I have done the required changes

**Comment by Iliveinbianries** [comment]
Great, just one thing you missed out, Make a separate main folder for Web, dont add this into Coding folder.

**Comment by Radhey644** [comment]
i have done the required changes

**Comment by Iliveinbianries** [comment]
Great work ✅.
If you have more ideas to work on feel free to open more issues and PRs.
Have a great day :)

**Comment by Radhey644** [comment]
If I contributed more on the same development file will it be shown in my hacktoberfest as a second work?
If yes then i would love to work more for you

**Pull request merged**
